#pragma once

enum AppState {
  STATE_CLOCK,
  STATE_TIMER_VIEW,
  STATE_TIMER_EDIT,
  STATE_TIMER_ALARM,
  STATE_STOPWATCH,
  STATE_REMINDER_HOME,
  STATE_REMINDER_LIST,
  STATE_REMINDER_EDIT,
  STATE_REMINDER_ALARM,
  STATE_SETTINGS_HOME,
  STATE_SETTINGS_MENU,
  STATE_SETTINGS_EDIT
};
